version: '3.9'
services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=school

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
